name: simple_rest_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  shelf:
  shelf_router: 
  shelf_multipart:
  http_parser: 
  path: 
  http: ^1.3.0
  shelf_cors_headers: ^0.1.5


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
